[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov htmlcov"
testpaths =  ["tests"]
norecursedirs = ["_test*"]   # To suppress the tests of `fairytool` template tests.

